# Generated by Django 5.2.13 on 2026-05-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FISICA', 'Física'), ('VIRTUAL', 'Virtual')], max_length=10)),
                ('capacidad', models.PositiveIntegerField()),
                ('equipo', models.TextField(blank=True, null=True)),
                ('link_zoom', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('facultad', models.CharField(max_length=150)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('facultad', models.CharField(max_length=150)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('facultad', models.CharField(max_length=150)),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('cupo_maximo', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='grupos', to='horarios.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horarios.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='horarios.profesor')),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.profesor')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLASE', 'Clase Normal'), ('EXAMEN', 'Examen'), ('TALLER', 'Taller'), ('OTRO', 'Otro')], default='CLASE', max_length=10)),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='horarios.aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='horarios.grupo')),
            ],
            options={
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDANZA', 'Tardanza'), ('JUSTIFICADO', 'Justificado')], max_length=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='horarios.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='horarios.sesion')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'sesion', 'fecha'), name='una_asistencia_por_sesion')],
            },
        ),
    ]
