# Generated by Django 6.0.5 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Información'), ('ALERTA', 'Alerta'), ('URGENTE', 'Urgente')], default='INFO', max_length=10),
        ),
    ]
